JAMAB_homepage:
    pattern:  /
    defaults: { _controller: JazzywebAulasMentorAlimentosBundle:Default:index }
    
JAMAB_listar:
    pattern:  /listar
    defaults: { _controller: JazzywebAulasMentorAlimentosBundle:Default:listar }

JAMAB_insertar:
    pattern:  /insertar
    defaults: { _controller: JazzywebAulasMentorAlimentosBundle:Default:insertar }

JAMAB_buscar:
    pattern:  /buscar
    defaults: { _controller: JazzywebAulasMentorAlimentosBundle:Default:buscarPorNombre }

JAMAB_buscarEnergia:
    pattern:  /buscarPorEnergia
    defaults: { _controller: JazzywebAulasMentorAlimentosBundle:Default:buscarPorEnergia }    

JAMAB_buscarCombinada:
    pattern:  /buscaCombinada
    defaults: { _controller: JazzywebAulasMentorAlimentosBundle:Default:buscarCombinada }    

JAMAB_ver:
    pattern:  /ver/{id}/
    defaults: { _controller: JazzywebAulasMentorAlimentosBundle:Default:ver }   