parameters:
#    finanzas.example.class: Casa\FinanzasBundle\Example

services:
#    finanzas.example:
#        class: %finanzas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
